# Stage 1: Build Stage
FROM ubuntu:22.04 AS builder
WORKDIR /app
COPY . /app

# Stage 2: Production Stage
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
