name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ash2ccode/javascript-clock .
    - name: Docker container run
      run: docker container run -dt -p 8086:80 ash2code/javascript-clock
